export enum NEWS_ACTION_TYPES {
  SET_FASHION_NEWS = 'SET_FASHION_NEWS',
  SET_LOADING_FASHION_NEWS = 'SET_LOADING_FASHION_NEWS',
  SET_ERROR_FASHION_NEWS = 'SET_ERROR_FASHION_NEWS',
  SET_SPORTS_NEWS = 'SET_SPORTS_NEWS',
  SET_LOADING_SPORTS_NEWS = 'SET_LOADING_SPORTS_NEWS',
  SET_ERROR_SPORTS_NEWS = 'SET_ERROR_SPORTS_NEWS',
  SORT_NEWS_DESCENDING = 'SORT_NEWS_DESCENDING',
  SORT_NEWS_ASCENDING = 'SORT_NEWS_ASCENDING',
  SET_FILTERS = 'SET_FILTERS',
}
